version: '3.0'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - dbdata:$DBDATA
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  
  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - wordpress:$VOLUME_WORDPRESS
    networks:
      - app-network

  web:
    depends_on:
      - wordpress
    image: nginx:1.23.2-alpine
    container_name: webserver
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - wordpress:$VOLUME_WORDPRESS
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
  
volumes: 
   wordpress:
   dbdata:

networks:
  app-network:
    driver: bridge
